### ISSUE TITLE
97.2% of the lib size is Ramda + Most.js

### ISSUE THREAD

**Issue by gustavopch** [semmel/on-screen-keyboard-detector#12]
This lib has about 250 SLoC, but it weighs 12.6kB gzipped because it brings a lot of stuff from Ramda and Most.js. Is there any chance it can be rewritten in plain JS? The two major benefits would be:

- It would probably go down to less than 1kB gzipped
- It would be easier for people to contribute, debug if needed, or even just quickly read the code and learn how it works without the need to understand how Ramda and Most.js work

![image](https://user-images.githubusercontent.com/10941958/146015494-f2894416-de0e-46e4-8b68-6c8b677adb75.png)
https://bundlephobia.com/package/on-screen-keyboard-detector@2.3.0

**Comment by semmel** [comment]
@gustavopch Your analysis is fine. Nevertheless, I will not rewrite the code in another style (e.g. object-oriented or procedural), unless someone pays me to do it. 

I think encapsulating the data in objects — which need an elaborate interface to be useful — is the wrong model for JS in the browser. Unfortunately most browser APIs are modelled that way.  Hence I need those "adapter" tool belt libraries Ramda and Most to liberate the data and let it flow from function to function.

The only rewrite I could imagine would involve more TypeScript, and replacing [Ramda](https://ramdajs.com) by [fp-ts](https://gcanti.github.io/fp-ts/).

> It would probably go down to less than 1kB gzipped

Given the popularity of Ramda, a larger application could probably already include it, or even Most.

> It would be easier for people to contribute, debug if needed, or even just quickly read the code and learn how it works without the need to understand how Ramda and Most.js work

I agree, this is a problem. However, PRs don't need to be perfect and can be jointly worked on to make them acceptable.

**Comment by gustavopch** [comment]
Alright. So I'm closing this issue.

**Comment by PeterKottas** [comment]
Seems like @semmel is open to supporting this in some capacity (at least merging it in), maybe it might be worth keeping this open? Somebody might find it and contribute the work needed here.
