### ISSUE TITLE
Usage of screen.orientation.type fails on desktop Safari

### ISSUE THREAD

**Issue by zhicong** [semmel/on-screen-keyboard-detector#6]
I had to roll back my use of this package because it crashes on browsers where `screen.orientation.type` is not supported, most notably on desktop Safari. 😔

https://github.com/semmel/on-screen-keyboard-detector/blob/861e2bcc8703f2a6975d235ff2783fd3f2930448/src/osk-detector.js#L19

Here's the compatibility table: https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation

I hope you're able to implement this without using the screen.orientation API, or if not add these unsupported browsers to the limitations in the README!

**Comment by semmel** [comment]
`screen.orientation` is a matter of 
```javascript 
/iPhone/.test(navigator.userAgent)
```
which leaves iPad out. Should'nt have done user agent sniffing perhaps...

I'll investigate to support iPad.

Opera Mini of course will never work.

**Comment by semmel** [comment]
iPad now supported in version 2.2.0.

With the exception of the [predictive text suggestion bar](https://support.apple.com/guide/ipad/use-predictive-text-ipad736a3ca8/ipados) showing with external keyboards. This is not detected as visible keyboard.

I've found detecting that to be pretty unpredictive. PRs/ideas welcome.

Thanks for reporting!
